languages:
  JavaScript: true
  PHP: true

engines:
  eslint:
    enabled: true
  phpcodesniffer:
    enabled: true
    config:
      file_extensions: "php"
  phpmd:
    enabled: true

ratings:
  paths:
  - "**.js"
  - "**.php"
exclude_paths:
  - vendor/**/*
