engines:
  duplication:
    enabled: true
    config:
      languages:
      - php
  eslint:
    enabled: true
  phpcodesniffer:
    enabled: true
    config:
      file_extensions: "php"
  phpmd:
    enabled: true
ratings:
  paths:
  - "bootstrap.php"
  - "locale/config.js"
