languages:
  javascript: true
  php: true

engines:
  eslint:
    enabled: true
  phpcodesniffer:
    enabled: true
    config:
      file_extensions: "php"
  phpmd:
    enabled: true

ratings:
  paths:
  - "**.php"
  - "**.js"
exclude_paths:
  - vendor/**/*
