language: php

php:
  - 5.5
  - 5.6
  - 7.0
  - hhvm

matrix:
  allow_failures:
    - php: hhvm
  fast_finish: true

before_script:
  - curl -s http://getcomposer.org/installer | php
  - php composer.phar install

script:
  - php composer.phar style
  - php composer.phar test

sudo: false
