language: php

php:
  - 5.5
  - 5.6
  - 7.0
  - hhvm

matrix:
  allow_failures:
    - php: 7.0
    - php: hhvm
  fast_finish: true

sudo: false

before_install:
  - phpenv config-rm xdebug.ini
  - php --version
  - composer self-update
  - composer --version

install:
  - composer install

script:
  - vendor/bin/phpunit --verbose --coverage-clover build/logs/clover.xml

after_script:
  - vendor/bin/test-reporter

addons:
  code_climate:
    repo_token:
      secure: "szG6TjoO0F+g5CxmrfrNhIUgFv5jlDAV2W9/n8baEkciAdFEqETPQHJGF4KqZ26mJFRajkIiyJDgrY4Dwm05v2z5m8sSNooBbdUR7/IPToGsP47Ekjc2X8FBGhn1OuBhWKzR/DN6QHChXu1UdINIjKBZb7eNvFfh16+euJ8fDKf3HDwXJKPCepP6IJ6xh6W41pXfdhQ3oHpOShC2N68h+Sr28WOf70IViF6kbpnQe9n6v28DshEMNTzlT6Sut3p+3NI08+2MT0+RXLdVdn1ZRO0jxWD4U8SC4ldJgzTwJMlF7+RPUvPuVtldHsMcHdFmw/Qhsx0BL5LG2H35tROWoQMpbwLd3bZdbLPehw4pUxm9XIgHwOzC2S4dsWbLqpRZf69SWulvxaW9OniVUNBxLHeOkyvj+oRKZ2n5C9KbC1Q3T4XFnbJAyrtqbIDTsAblKbWPY42s7gnKK7aE6bHy4KjWx4YMBeMUdGDdgs3W7TQ2z7Fek5ylQdkQkXHqy2C1fo1lBwqTicxvGEvBu4oNP1BDWa7YWlLDERXOaaZ7H46KEaYNbc2UFHi/bINn7DQdaNK83iLb9nlWlwP1MiHf8jYpOtPyxM4BmewO83wwa6KFMtuJAvKv46PsI3vJO+ZObR3YVope1+bQaU7smRkc2s2/sfnUE/iJd90iGGKpklk="

notifications:
  email:
    on_failure: change
