language: php

php:
  - 5.5
  - 5.6
  - 7.0
  - hhvm

matrix:
  allow_failures:
    - php: 7.0
    - php: hhvm
  fast_finish: true

sudo: false

install:
  - curl -s http://getcomposer.org/installer | php
  - php composer.phar install

script:
  - php composer.phar style

after_script:
  - vendor/bin/test-reporter

notifications:
  email: change
